from math import pi

SEPARADOR = "=" * 40
VERSAO = "ELETROCALC v0.1"
TITULO_MENU_PRINCIPAL = "ELETROCALC"
TITULO_MENU_LEI_DE_OHM = "LEI DE OHM"
TITULO_MENU_POTENCIA = "POTÊNCIA"
TITULO_MENU_REAT_CAP = "REATÂNCIA CAPACITIVA"
TITULO_MENU_REAT_IND = "REATÂNCIA INDUTIVA"
ESPACOS = 14 * " "
ESPACOS_DOIS = 9 * " "
PI = pi
FREQUENCIA_PADRAO = 60
OHM = "Ω"
VOLT = "V"
AMPERE = "A"
WATT = "W"
VOLT_AMPERE = "VA"
VOLT_AMPERE_REATIVO = "VAR"
HERTZ = "Hz"
HENRY = "H"
FARAD = "F"