SEPARADOR = "=" * 40
VERSAO = "ELETROCALC v0.1"
TITULO_MENU_PRINCIPAL = "ELETROCALC"
TITULO_MENU_LEI_DE_OHM = "LEI DE OHM"
TIULO_MENU_POTENCIA = "POTÊNCIA"
TITULO_MENU_REAT_CAP = "REATÂNCIA CAPACITIVA"
TITULO_MENU_REAT_IND = "REATÂNCIA INDUTIVA"
ESPACOS = 14 * " "
ESPACOS_DOIS = 9 * " "
MSG_OPCAO = "Escolha uma opção: "
MSG_DOIS_VALORES = "Digite dois valores e deixe um em branco"
MSG_FIM = "Até mais"
PI = 3.14159
FREQUENCIA_PADRAO = 60