from math import pi

SEPARADOR = "=" * 41
VERSAO = "v0.1"
LARGURA = 41
TITULO_MENU_PRINCIPAL = "ELETROCALC"
TITULO_MENU_LEI_DE_OHM = "LEI DE OHM"
TITULO_MENU_POTENCIA = "POTÊNCIA"
TITULO_MENU_REAT_CAP = "REATÂNCIA CAPACITIVA"
TITULO_MENU_REAT_IND = "REATÂNCIA INDUTIVA"
TITULO_MENU_POTENCIAS = "POTÊNCIA ELÉTRICA"
TITULO_MENU_POTENCIA_APARENTE = "POTÊNCIA APARENTE"
TITULO_MENU_POTENCIA_ATIVA = "POTÊNCIA ATIVA"
TITULO_MENU_POTENCIA_REATIVA = "POTÊNCIA REATIVA"
FORMULA_POTENCIA_ATIVA_TENSAO_CORRENTE_FATOR_DE_POTENCIA = "P = V * I * cos(φ°)"
FORMULA_POTENCIA_ATIVA_POTENCIA_APARENTE_FATOR_DE_POTENCIA = "P = S * cos(φ°)"
FORMULA_POTENCIA_ATIVA_POTENCIA_APARENTE_POTENCIA_REATIVA = "P = √(S² - Q²)"
FORMULA_POTENCIA_APARENTE_TENSAO_CORRENTE = "S = E x I"
FORMULA_POTENCIA_APARENTE_POTENCIA_ATIVA_FATOR_DE_POTENCIA = "S = P / FP"
FORMULA_POTENCIA_APARENTE_POTENCIA_ATIVA_POTENCIA_REATIVA = "S = √(P² + Q²)"
FORMULA_POTENCIA_REATIVA_TENSAO_CORRENTE_ANGULO = "Q = V * I * sin(θ°)"
FORMULA_POTENCIA_REATIVA_POTENCIA_APARENTE_POTENCIA_ATIVA = "Q = √(S² - P²)"
FORMULA_POTENCIA_REATIVA_POTENCIA_ATIVA_ANGULO = "Q = P * tan(φ°)"
FORMULA_REATANCIA_CAPACITIVA = "Xc = 1 / (2 * π * ƒ * C)"
FORMULA_LEI_DE_OHM = "I = E / R"
FORMULA_REATANCIA_INDUTIVA = "XL = 2 * π * ƒ * L"
FORMULA_POTENCIA_ATIVA = "P = E x I"
OPCOES_MENU_PRINCIPAL = [
    "Lei de Ohm",
    "Potência Elétrica",
    "Reatância Indutiva",
    "Reatância Capacitiva",
]
OPCOES_MENU_POTENCIAS = [
    "Potência Ativa",
    "Potência Reativa",
    "Potência Aparente",
    "Fator de Potência",
]
OPCOES_MENU_POTENCIA_APARENTE = [
    "Tensão (V) + Corrente (A)",
    "Potência Ativa (W) + Fator de Potência",
    "Potência Ativa (W) + Potência Reativa (Var)",
]
OPCOES_MENU_POTENCIA_ATIVA = [
    "Tensão (v) + Corrente (A) + Fator de Potência",
    "Potência Aparente (VA) + Fator de Potência",
    "Potência Aparente (VA) + Potência Reativa (Var) ",
]
OPCOES_MENU_POTENCIA_REATIVA = [
    "Tensão (v) + Corrente (A) + Ângulo",
    "Potência Aparente (VA) + Potência Ativa (W)",
    "Potência Ativa (W) + Ângulo (°) ",
]
SELETOR_MENU_POTENCIA_ATIVA = ["s", "v", "c", "1", "2", "3"]
SELETOR_MENU_PRINCIPAL = ["s", "1", "2", "3", "4"]
SELETOR_MENU_POTENCIAS = ["s", "v", "c", "1", "2", "3", "4"]
SELETOR_MENU_POTENCIA_APARENTE = ["s", "v", "c", "1", "2", "3"]
SELETOR_MENU_POTENCIA_REATIVA = ["s", "v", "c", "1", "2", "3"]
PI = pi
FREQUENCIA_PADRAO = 60
OHM = "Ω"
VOLT = "V"
AMPERE = "A"
WATT = "W"
VOLT_AMPERE = "VA"
VOLT_AMPERE_REATIVO = "VAR"
HERTZ = "Hz"
HENRY = "H"
FARAD = "F"
GRAUS = "°"
